### ISSUE TITLE
Hoppers issue with DoubleChest

### ISSUE THREAD

**Issue by Infernus101** [CortexPE/TeaSpoon#331] opened 2018-11-13 23:18 UTC
Hoppers still crashing the server, dont know how to reproduce the error:

> 2018-11-13 [15:32:11] [Server thread/CRITICAL]: Error: "Call to a member function getSize() on null" (EXCEPTION) in "src/pocketmine/inventory/DoubleChestInventory" at line 63
2018-11-13 [15:32:11] [Server thread/DEBUG]: #0 src/pocketmine/tile/Hopper(132): pocketmine\inventory\DoubleChestInventory->getItem(integer 0)
2018-11-13 [15:32:11] [Server thread/DEBUG]: #1 src/pocketmine/level/Level(755): pocketmine\tile\Hopper->onUpdate()
2018-11-13 [15:32:11] [Server thread/DEBUG]: #2 src/pocketmine/Server(2358): pocketmine\level\Level->doTick(integer 3072)
2018-11-13 [15:32:11] [Server thread/DEBUG]: #3 src/pocketmine/Server(2507): pocketmine\Server->checkTickUpdates(integer 3072, double 1542148331.1397)
2018-11-13 [15:32:11] [Server thread/DEBUG]: #4 src/pocketmine/Server(2253): pocketmine\Server->tick()
2018-11-13 [15:32:11] [Server thread/DEBUG]: #5 src/pocketmine/Server(2131): pocketmine\Server->tickProcessor()
2018-11-13 [15:32:11] [Server thread/DEBUG]: #6 src/pocketmine/Server(1700): pocketmine\Server->start()
2018-11-13 [15:32:11] [Server thread/DEBUG]: #7 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string servers/server4/, string servers/server4/plugins/)
2018-11-13 [15:32:11] [Server thread/DEBUG]: #8 servers/server4/PocketMine-MP.phar(1): require(servers/server4/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
2018-11-13 [15:32:11] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2018-11-13 [15:32:11] [Server thread/EMERGENCY]: Please upload the "servers/server4/crashdumps/Tue_Nov_13-15.32.11-MST_2018.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can

**Comment by teracube** [comment] 2018-11-14 03:39
@Infernus101
duplicate of #322

**Comment by Infernus101** [comment] 2018-11-14 08:11
but the error is different... @teracube

**Closed** 2018-11-15 19:46 UTC

**Comment by isoz** [comment] 2018-11-16 14:53
I still have it, had to turn them off and now kids are mad.

**Comment by teracube** [comment] 2018-11-16 15:09
@isoz 
could you please turn  hoppers ON and test with this latest stable PMMP build

https://jenkins.pmmp.io/job/PocketMine-MP/1642/

no crash for me since 3 days

**Comment by Infernus101** [comment] 2018-11-16 15:09
> @isoz
> could you please turn hoppers ON and test with this latest stable PMMP build
> 
> https://jenkins.pmmp.io/job/PocketMine-MP/1642/
> 
> no crash for me since 3 days

agreed
