### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by Emis02** [CortexPE/TeaSpoon#79] opened 2017-12-08 18:49 UTC
Please give me this plugin but compatible with alpha 7 you would be very useful. Sorry for my english but I'm italian

**Comment by Emis02** [comment] 2017-12-08 18:51
It makes me wrong but in alpha 7 you do not have anything like this?

**Comment by Emis02** [comment] 2017-12-08 18:55
[Server thread/CRITICAL]: Error: "Call
 to undefined method pocketmine\command\SimpleCom
mandMap::unregister()" (EXCEPTION) in "plugins/Te
aSpoon-master/src/CortexPE/commands/CommandManage
r" at line 68

**Comment by SuperKali** [comment] 2017-12-08 20:47
@CortexPE poor boy, you don't need any plugin, this plugin is only for 1.2.x. but you cant update you server  on 1.2.x?, because your server is outdated!

**Comment by SuperKali** [comment] 2017-12-08 20:50
@Emis02 please you close this issue because your server is outdated, isn't any sense this issue

**Comment by Emis02** [comment] 2017-12-08 20:51
Kali did your business, nobody asked you anything. I asked for a favor

**Comment by SuperKali** [comment] 2017-12-08 20:54
@Emis02 I do not want to repeat the same thing, please close this issue your server is outdated ok?
do not seek help and do you make the plugins!

**Comment by TheNewManu** [comment] 2017-12-08 21:29
Hahahahaha I die

**Comment by SuperKali** [comment] 2017-12-08 21:44
GG

**Comment by NycuRO** [comment] 2017-12-08 21:52
Closed. Cannot reproduce, plugin it's perfect functionaly. Plugin was only for latest versions, thanks. If you want for oldest version, it's your problem.

**Closed by NycuRO** 2017-12-08 21:52 UTC
