### ISSUE TITLE
Crafting isn't working when installed last  pmmp 1.2.13 #920

### ISSUE THREAD

**Issue by alvin0319** [CortexPE/TeaSpoon#236] opened 2018-04-08 03:10 UTC
## Issue Description

A short description about the issue

## Steps to Reproduce

1. Adding the teaspoon last bulid in plugin forder
2. In surviver mode, you can't crafting
3. ...

## Crashdump, Backtrace or Other Files
there are no have crashdump or error
```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by MasterOfTheRealm** [comment] 2018-04-08 03:14
Duplicate of #235

**Closed** 2018-04-08 04:43 UTC
